<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>A3E Technologies Ltd</title>
    <link rel="stylesheet" href="./assets/css/app.css">
    <link rel="stylesheet" href="https://fonts.google.com/?query=ubuntu">
</head>
<body class="liter-regular">
    
    <div id="intro" class="section">
        <h1 class="headert1 centeredText">Driven by Excellence, Powered by Innovation</h1>
        <p>Specializing in efficiency enhancing software for small businesses.</p>
        <button class="button">More</button>
    </div>
    <div id="about" class="section">
        <div class="aboutLeft">
            <h1>Innovative Software Solutions for Small Businesses</h1>
            <p>At A3E Technologies Ltd, we specialize in developing software solutions that enhance efficiency for small businesses, including our flagship tool management app, ToolBeeQr.</p>
        </div>
        <div class="aboutRight">
            <img src="./assets/images/christopher-burns-8KfCR12oeUM-unsplash.jpg" alt="picture1" class="samplepic1">
        </div>
    </div>
    <div id="services" class="section">
        <h1>Custom Software Solutions</h1>
        <p>We develop tailored software to enhance efficiency for small businesses, driving growth and productivity.</p>
    </div>
</body>