<?php include 'views/navbar.phtml'; ?>
<body class="liter-regular">
    
    <div id="intro" class="section flex gap-5">
        <h1 class="xl:text-9xl lg:text-7xl text-center w-[80vw] p-10">Driven by Excellence, Powered by Innovation</h1>
        <p class="text-xl">Specializing in efficiency enhancing software for small businesses.</p>
        <button class="button">More</button>
    </div>
    <div id="about" class="section  flex gap-10">
        <div class="w-[50vw] h-[100vh] flex flex-col gap-10 p-10 ">
            <h1 class="xl:text-8xl lg:text-7xl">Innovative Software Solutions for Small Businesses</h1>
            <p class="text-3xl text-start xl:w-[10w]">At A3E Technologies Ltd, we specialize in developing software solutions that enhance efficiency for small businesses, including our flagship tool management app, ToolBeeQr.</p>
            <button class="bg-[#9c8930] rounded-3xl w-[20vw] hover:bg-slate-600">Contact Us</button>
        </div>
        <div class="w-[50vw] h-[50vh] flex justify-start items-center">
            <img src="../assets/images/christopher-burns-8KfCR12oeUM-unsplash.jpg" alt="picture1" class="samplepic1 object-fill w-[100vw] h-[60vh] rounded-3xl flex justify-start">
        </div>
    </div>
    <div id="services" class="section flex flex-col gap-5">
        <h1 class="xl:text-8xl lg:text-7xl">Custom Software Solutions</h1>
        <div class="w-[60vw]">
            <p class="text-xl text-center">We develop tailored software to enhance efficiency for small businesses, driving growth and productivity.</p>
        </div>
        <div class="flex lg:flex-row gap-5 sm:flex-col ">
            <div class="w-[30vw] flex flex-col gap-3">
                <img src="../assets/images/laptop-2620118_1920.jpg" alt="" class="object-contain rounded-3xl">
                <h3 class="text-3xl text-[#e6d7b8]">Expert Development Team</h3>
                <p class="text-xl ">Our skilled developers create innovative solutions, ensuring your business stays competitive and efficient.</p>
            </div>
            <div class="w-[30vw] flex flex-col gap-3">
                <img src="../assets/images/digital-marketing-1433427_1920.jpg" alt="" class="object-contain rounded-3xl">
                <h3 class="text-3xl text-[#e6d7b8]">Tailored Solutions</h3>
                <p class="text-xl">We provide personalized software development services that align with your unique business needs and goals.</p>
            </div>
        </div>
    </div>
</body>

<?php include 'views/footer.phtml'; ?>
