<?php include 'views/navbar.phtml'; ?>

<body class="liter-regular">
    <div class=" flex flex-col  items-center gap-10">
        <div class="p-10">
            <h1 class="xl:text-9xl lg:text-7xl text-center w-[80vw]">ToolBeeQR</h1>
            <p class="text-center">Time to bee organized!</p>
        </div>
        


        <div class="flex gap-10">
            <div class="w-[40vw]">
                <p class="text-3xl xl:text-4xl text-[#e6d7b8]">The ultimate inventory management solution for small businesses and freelancers in the construction industry.</p>
                <p class="text-xl xl:text-3xl pt-20 pb-10">Managing tools and inventory just got easier! ToolBeeQR is an intuitive inventory management app designed specifically for small businesses and freelancers in the construction sector. With powerful QR code scanning, seamless item transfers, and a user-friendly interface, keeping track of your equipment has never been more efficient.</p>
                <button class="bg-[#9c8930] rounded-3xl font-bold py-3 px-5 hover:bg-slate-600">Book A Demo</button>
            </div>
            <div class="w-[40vw]">
                <img src="../assets/images/ra-dragon-1LWXx9kwlLw-unsplash.jpg" alt="" class="rounded-3xl">
            </div>
        </div>

        <div>
            <h1 class="text-7xl text-center py-[5vh]">Key Features:</h1>
            <div class="flex flex-wrap gap-5">

                <div class="flex flex-col gap-5 bg-[#161616] w-[20vw] h-[30vh] justify-center">
                    <h4 class="text-2xl text-center text-[#e6d7b8]">QR Code Scanning </h4>
                    <p class="text-l text-center">Quickly scan and update inventory in real time.</p>
                </div>
                <div class="flex flex-col gap-5 bg-[#161616] w-[20vw] h-[30vh] justify-center">
                    <h4 class="text-2xl text-center text-[#e6d7b8]">Item Transfers</h4>
                    <p class="text-l text-center">Easily move tools between team members with a simple transfer system.</p>
                </div>
                <div class="flex flex-col gap-5 bg-[#161616] w-[20vw] h-[30vh] justify-center">
                    <h4 class="text-2xl text-center text-[#e6d7b8]">Check-In Function</h4>
                    <p class="text-l text-center">Ensure accountability by tracking tools as they are checked in.</p>
                </div>
                <div class="flex flex-col gap-5 bg-[#161616] w-[20vw] h-[30vh] justify-center">
                    <h4 class="text-2xl text-center text-[#e6d7b8]">User-Friendly Interface</h4>
                    <p class="text-l text-center">Designed for efficiency, making inventory management hassle-free.</p>
                </div>
            </div>

        </div>

        <div class="flex gap-[5vw] px-[20vh] xl:px-[30vh]">
            <div class="">
                <img src="../assets/images/toolbeescreenshots/image00002.png" alt="" class="object-contain">
            </div>
            <div class="">
                <img src="../assets/images/toolbeescreenshots/image00005.png" alt="" class="object-contain">
            </div>
            <div class="">
                <img src="../assets/images/toolbeescreenshots/image00009.png" alt="" class="object-contain">
            </div>
        </div>
        <section class="embla">
            <div class="embla__viewport">
                <div class="embla__container">
                <div class="embla__slide">
                    <div class="embla__slide__number">1</div>
                </div>
                <div class="embla__slide">
                    <div class="embla__slide__number">2</div>
                </div>
                <div class="embla__slide">
                    <div class="embla__slide__number">3</div>
                </div>
                <div class="embla__slide">
                    <div class="embla__slide__number">4</div>
                </div>
                <div class="embla__slide">
                    <div class="embla__slide__number">5</div>
                </div>
                </div>
            </div>

            <div class="embla__controls">
                <div class="embla__buttons">
                <button class="embla__button embla__button--prev" type="button">
                    <svg class="embla__button__svg" viewBox="0 0 532 532">
                    <path
                        fill="currentColor"
                        d="M355.66 11.354c13.793-13.805 36.208-13.805 50.001 0 13.785 13.804 13.785 36.238 0 50.034L201.22 266l204.442 204.61c13.785 13.805 13.785 36.239 0 50.044-13.793 13.796-36.208 13.796-50.002 0a5994246.277 5994246.277 0 0 0-229.332-229.454 35.065 35.065 0 0 1-10.326-25.126c0-9.2 3.393-18.26 10.326-25.2C172.192 194.973 332.731 34.31 355.66 11.354Z"
                    ></path>
                    </svg>
                </button>

                <button class="embla__button embla__button--next" type="button">
                    <svg class="embla__button__svg" viewBox="0 0 532 532">
                    <path
                        fill="currentColor"
                        d="M176.34 520.646c-13.793 13.805-36.208 13.805-50.001 0-13.785-13.804-13.785-36.238 0-50.034L330.78 266 126.34 61.391c-13.785-13.805-13.785-36.239 0-50.044 13.793-13.796 36.208-13.796 50.002 0 22.928 22.947 206.395 206.507 229.332 229.454a35.065 35.065 0 0 1 10.326 25.126c0 9.2-3.393 18.26-10.326 25.2-45.865 45.901-206.404 206.564-229.332 229.52Z"
                    ></path>
                    </svg>
                </button>
                </div>

                <div class="embla__dots"></div>
            </div>
        </section>
    </div>
    <script src="../assets/js/carousel.js"></script>


</body>
<?php include 'views/footer.phtml'; ?>